
import { BentoCardData } from './types';

export const INITIAL_CARDS: BentoCardData[] = [
  {
    id: 'calendar-1',
    type: 'greeting',
    title: 'Calendar',
    size: 'small',
    theme: 'default',
    order: 0,
  },
  {
    id: 'links-personal',
    type: 'links',
    title: 'Personal',
    size: 'small',
    theme: 'default',
    order: 1,
    links: [
      { id: 'p1', label: 'Gmail', url: 'https://mail.google.com' },
      { id: 'p2', label: 'Google Keep', url: 'https://keep.google.com' },
      { id: 'p3', label: 'Google Drive', url: 'https://drive.google.com' },
      { id: 'p4', label: 'Amazon Photos', url: 'https://www.amazon.com/photos' },
      { id: 'p5', label: 'Google Photos', url: 'https://photos.google.com' },
      { id: 'p6', label: 'FaceBook', url: 'https://facebook.com' },
      { id: 'p7', label: 'Yahoo Mail', url: 'https://mail.yahoo.com' },
    ],
  },
  {
    id: 'links-favorites',
    type: 'links',
    title: 'Favorites',
    size: 'small',
    theme: 'default',
    order: 2,
    links: [
      { id: 'f1', label: 'LinkedIn', url: 'https://linkedin.com' },
      { id: 'f2', label: 'Reddit', url: 'https://reddit.com' },
      { id: 'f3', label: 'X.com', url: 'https://x.com' },
      { id: 'f4', label: 'Figma', url: 'https://figma.com' },
      { id: 'f5', label: 'Youtube', url: 'https://youtube.com' },
      { id: 'f6', label: 'Amazon', url: 'https://amazon.com' },
      { id: 'f7', label: 'ESPN', url: 'https://espn.com' },
    ],
  },
  {
    id: 'search-1',
    type: 'search',
    title: 'Quick Search',
    size: 'small',
    theme: 'default',
    order: 3,
  },
  {
    id: 'news-1',
    type: 'news',
    title: 'Reddit News',
    size: 'medium',
    theme: 'default',
    order: 4,
  },
  {
    id: 'links-news',
    type: 'links',
    title: 'News',
    size: 'small',
    theme: 'default',
    order: 5,
    links: [
      { id: 'n1', label: 'BBC', url: 'https://www.bbc.com' },
      { id: 'n2', label: 'Reddit', url: 'https://www.reddit.com' },
      { id: 'n3', label: 'Imdb', url: 'https://www.imdb.com' },
      { id: 'n4', label: 'New York Times', url: 'https://www.nytimes.com' },
      { id: 'n5', label: 'Washington Post', url: 'https://www.washingtonpost.com' },
      { id: 'n6', label: 'LA Times', url: 'https://www.latimes.com' },
      { id: 'n7', label: 'TechCrunch', url: 'https://techcrunch.com' },
    ],
  },
  {
    id: 'links-inspiration',
    type: 'links',
    title: 'Inspiration',
    size: 'small',
    theme: 'default',
    order: 6,
    links: [
      { id: 'i1', label: 'Awwwards', url: 'https://www.awwwards.com' },
      { id: 'i2', label: 'Dribbble', url: 'https://dribbble.com' },
      { id: 'i3', label: 'Godly', url: 'https://godly.website' },
      { id: 'i4', label: 'Pinterest', url: 'https://pinterest.com' },
      { id: 'i5', label: 'Behance', url: 'https://behance.net' },
    ],
  },
  {
    id: 'links-entertainment',
    type: 'links',
    title: 'Entertainment',
    size: 'small',
    theme: 'default',
    order: 7,
    links: [
      { id: 'e1', label: 'Amazon Prime', url: 'https://www.primevideo.com' },
      { id: 'e2', label: 'Netflix', url: 'https://netflix.com' },
      { id: 'e3', label: 'Hulu', url: 'https://hulu.com' },
      { id: 'e4', label: 'Crunchyroll', url: 'https://crunchyroll.com' },
      { id: 'e5', label: 'TikTok', url: 'https://tiktok.com' },
      { id: 'e6', label: 'Disney+', url: 'https://disneyplus.com' },
      { id: 'e7', label: 'Paramount+', url: 'https://paramountplus.com' },
      { id: 'e8', label: 'Viki', url: 'https://viki.com' },
      { id: 'e9', label: 'Spotify', url: 'https://spotify.com' },
      { id: 'e10', label: 'PBS Frontline', url: 'https://www.pbs.org/wgbh/frontline/' },
    ],
  },
  {
    id: 'directions-1',
    type: 'directions',
    title: 'Directions',
    size: 'small',
    theme: 'gray',
    order: 8,
  }
];

export const THEMES = {
  default: 'bg-white text-slate-900 border border-slate-200',
  blue: 'bg-blue-50 text-blue-900 border border-blue-100',
  gray: 'bg-slate-100 text-slate-800 border border-slate-200',
  dark: 'bg-slate-700 text-white border border-slate-600',
  emerald: 'bg-emerald-50 text-emerald-900 border border-emerald-100',
  rose: 'bg-rose-50 text-rose-900 border border-rose-100',
  amber: 'bg-amber-50 text-amber-900 border border-amber-100',
  indigo: 'bg-indigo-50 text-indigo-900 border border-indigo-100',
};

export const SIZES = {
  small: 'col-span-1 row-span-1',
  medium: 'col-span-1 md:col-span-2 row-span-1 md:row-span-2',
  large: 'col-span-1 md:col-span-2 lg:col-span-3 row-span-2',
};